create table if not exists public.stafett_runners (
  id bigint generated by default as identity primary key,
  event_id text not null,
  stage int not null,
  name text not null,
  distance_km numeric not null,
  speed_kmh numeric not null,
  start_place text,
  finish_place text,
  updated_at timestamptz default now(),
  unique(event_id, stage)
);

create table if not exists public.stafett_actuals (
  id bigint generated by default as identity primary key,
  event_id text not null,
  stage int not null,
  finish_time time not null,
  updated_at timestamptz default now(),
  unique(event_id, stage)
);

alter table public.stafett_runners enable row level security;
alter table public.stafett_actuals enable row level security;

-- Åpen skriving/lesing for alle med lenken. Bruk kun til dette arrangementet.
drop policy if exists "public read runners" on public.stafett_runners;
create policy "public read runners" on public.stafett_runners for select using (true);

drop policy if exists "public write runners" on public.stafett_runners;
create policy "public write runners" on public.stafett_runners for insert with check (true);

drop policy if exists "public update runners" on public.stafett_runners;
create policy "public update runners" on public.stafett_runners for update using (true) with check (true);

drop policy if exists "public read actuals" on public.stafett_actuals;
create policy "public read actuals" on public.stafett_actuals for select using (true);

drop policy if exists "public write actuals" on public.stafett_actuals;
create policy "public write actuals" on public.stafett_actuals for insert with check (true);

drop policy if exists "public update actuals" on public.stafett_actuals;
create policy "public update actuals" on public.stafett_actuals for update using (true) with check (true);

drop policy if exists "public delete actuals" on public.stafett_actuals;
create policy "public delete actuals" on public.stafett_actuals for delete using (true);
